### fixed values due to data collection settings
sampling_frequency : 50

data_cleansing : False
data_preparation : False
machine_learning : True




# subject selection
# set out of : ['all_subjects', 'test_subjects', 'relabeled_subjects', 'ocd_diagnosed_subjects', 'trustworthy_subjects']
selected_subject_option: 'relabeled_subjects'

all_subjects: [1, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13, 15, 18, 19, 20, 21, 22, 24, 25, 27, 29, 30]
ocd_diagnosed_subjects: [5, 9, 1, 3, 12, 13, 20, 24, 29, 30]
trustworthy_subjects: [1, 3, 4, 18, 20, 30]  # only 18 without a diagnosis
relabeled_subjects: [1, 3, 4, 18] #, 20, 30]
test_subjects : [1, 3, 4] # at least 3 for ml

untrustworthy_subjects : []  # TODO: rename this item and use it in order to e.g. create a different split

seed: 42

###################################################################
# DATA PREPROCESSING SETTINGS
###################################################################

### General settings
resample: True # TODO outdated?
balancing_option: "SMOTETomek"

use_filter: True
use_scaling: True


### Filtering Settings
test_filters : True  # if false, the system will use the first value in the list.
run_export : False  # actually save the results to the disk
short_succession_time : [1, 5, 10, 30]
magnitude_window_size : [200, 500, 2000]
magnitude_threshold : [0.1, 0.2, 0.3, 0.4, 0.5]
magnitude_overlap : [0, 0.5]
min_time_in_s_before_label: [5, 10]
# TODO: band filter settings? (where does it happen?)

### Relabel settings
relabel_duration : 38
relabel_offset : 5   # how many seconds before the label did the hand washing end?
# strategy, strategy parameters could be added here!


###################################################################
# DATA PREPARATION SETTINGS
###################################################################

save_data: True
overwrite_data: True  # Currently not Implemented!

### Settings for data windowing
window_size : 5 # value in seconds
test_window_size: 30
overlap : 0.5
labelling_algorithm : "Majority"

### Settings for butterworth filter
upper_threshold : 18
lower_threshold : 1
order : 3
columns : ['acc x', 'acc y', 'acc z', 'gyro x', 'gyro y', 'gyro z']

### Settings for feature scaling
scaler : "standard"

### Settings for feature extraction
id : "tsfresh_id"
raw_features : False  # don't extract features, just create windows. Overwrites filter and scaler setting.

features :
  mean: None
  standard_deviation: None
  maximum: None
  minimum": None
  mean_abs_change: None
  skewness: None
  kurtosis: None

jobs : 32

### plot settings

barchart_metric: "f1_score"

###################################################################
# MODEL SELECTION SETTINGS
###################################################################

all_models : True

models:
  - RandomForestClassifier: True
  - GradientBoostingClassifier: True
  - LogisticRegression: True
  - DummyClassifier: True

###################################################################
# Machine Learning Pipeline SETTINGS
###################################################################
run_deep_learning : False
run_classic_methods : True
