
relabeled_subjects: ['01','03','30','04','18','20'] # specify in files e.g. OCDetect_03 run_subject = "03", OCDetect_30 run_subject = "30"
# Merging settings
d_type_certain : LabelMergeParameter.Intersection # LabelMergeParameter.Intersection or LabelMergeParameter.Union
d_type_uncertain : LabelMergeParameter.Intersection # LabelMergeParameter.Intersection or LabelMergeParameter.Union
d_type_un_cert : LabelMergeParameter.IgnoreUncertain # LabelMergeParameter.Intersection or LabelMergeParameter.IgnoreUncertain

