- robin-pc:
    hostname: Robin-PC-Ubuntu
    data_folder: ../../../OCDetect_DATA/
    meta_subfolder: metadata/
    evals_subfolder: allEvaluations/
    dailies_subfolder: dailyQuestionnaire/
    annotations_subfolder: annotations/
    first_hw_subfolder: labels_first_handwashes/
    export_subfolder: ../../../OCDetect_Export/
    test_n_recs: 3
    test_n_subs: 3

- robin-laptop:
    hostname: thinkbook
    data_folder: ../../../../Datasets/OCDetect_DATA/
    meta_subfolder: metadata/
    evals_subfolder: allEvaluations/
    dailies_subfolder: dailyQuestionnaire/
    annotations_subfolder: annotations/
    first_hw_subfolder: labels_first_handwashes/
    export_subfolder: ../../../../Datasets/OCDetect_Export/

- kristina-mac:
    hostname: atlas
    data_folder: ../../datasets/OCDetect/
    meta_subfolder: metadata/
    first_hw_subfolder: labels_first_handwashes/
    prefix: OCDetect_
    output_folder: ../../OCDetect/Analysis/plots/idle_regions/
    export_subfolder: ../../datasets/OCDetect_Export/  # @kristina you may want to change this :)
