testing: !!bool true
#test_n_recs: 10
#test_n_subs: 10

ocd_diagnosed_subjects: ["05", "09", "01", "03", "12", "13", "20", "24", "29", "30"]
all_subjects: ["01", "02", "03", "04", "05", "07", "09", "10", "11", "12", "13", "15", "18", "19", "20", "21", "22", "24", "25", "27", "29", "30"]
subgroup: []

short_succession_time : 15  # time in seconds to consider labels too close to each other