### fixed values due to data collection settings
sampling_frequency : 50


testing: !!bool true
#test_n_recs: 10
#test_n_subs: 10

ocd_diagnosed_subjects: ["05", "09", "01", "03", "12", "13", "20", "24", "29", "30"]
#all_subjects: ["05", "09", "01", "03", "12", "13", "20", "24", "29", "30"]
all_subjects: ["01", "02", "03", "04", "05", "07", "09", "10", "11", "12", "13", "15", "18", "19", "20", "21", "22", "24", "25", "27", "29", "30"]
subgroup: []

### Filtering Settings
short_succession_time : 10
magnitude_window_size : 500
magnitude_threshold : 0.2
magnitude_overlap : 0.5
min_time_in_s_before_label: 5

### Relabel settings
relabel_duration : 38
relabel_offset : 5   # how many seconds before the label did the hand washing end?
# strategy, strategy parameters could be added here!

###################################################################
# MACHINE LEARNING SETTINGS
###################################################################

### Settings for conventional machine learning data preparation
window_size : 5 # value in seconds
overlap : 0.5
labelling_algorithm : "Majority"

### Settings for butterworth filter
upper_threshold : 18
lower_threshold : 1
order : 3
columns : ['acc x', 'acc y', 'acc z', 'gyro x', 'gyro y', 'gyro z']

### Settings for feature extraction
id : "tsfresh_id"

features :
  mean: None
  standard_deviation: None
  maximum: None
  minimum": None
  mean_abs_change: None
  skewness: None
  kurtosis: None

jobs : 32

### Settings for feature scaling
scaler : "standard"